### ISSUE TITLE
Docker build not working - mvnw permission denied etc

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#615]
Hello, I'm trying to install PLC4X with Docker and get a couple of errors - 

$ docker build -t plc4x .
...
Step 21/39 : COPY . /ws/
 \---\> e86e4d250f0c
Step 22/39 : WORKDIR /ws
 \---\> Running in b2d9525763e0
Removing intermediate container b2d9525763e0
 \---\> 2d714dffc27b
Step 23/39 : RUN ./mvnw -P with-boost,with-c,with-cpp,with-dotnet,with-go,with-logstash,with-opcua-werver,with-proxies,with-python,with-logstash,with-sandbox com.offbytwo.maven.plugins:maven-dependency-plugin:3.1.1.MDEP568:go-offline -DexcludeGroupIds=org.apache.plc4x,org.apache.plc4x.examples,org.apache.plc4x.sandbox
 \---\> Running in 97e09acbcdfd
/bin/sh: 1: ./mvnw: Permission denied
The command '/bin/sh -c ./mvnw -P with-boost,with-c,with-cpp,with-dotnet,with-go,with-logstash,with-opcua-werver,with-proxies,with-python,with-logstash,with-sandbox com.offbytwo.maven.plugins:maven-dependency-plugin:3.1.1.MDEP568:go-offline -DexcludeGroupIds=org.apache.plc4x,org.apache.plc4x.examples,org.apache.plc4x.sandbox' returned a non-zero code: 126

So I added a step to the Dockerfile line 72
 
RUN chmod ****x ./mvnw
That got it past that error, then got another one -

Non-resolvable parent POM for org.apache.plc4x.sandbox:plc4cpp:[unknown-version]: Could not find artifact org.apache.plc4x.sandbox:plc4x-sandbox:pom:0.8.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 24, column 11

I'm not familiar with maven so am not sure how to get past it...

Thank you for any help - 

 

Imported from Jira [PLC4X-284](https://issues.apache.org/jira/browse/PLC4X-284). Original Jira may contain additional context.
Reported by: bburnskm.

**Comment by maneetgoyal** [comment]
```
 => [build 20/24] RUN dos2unix .mvn/wrapper/maven-wrapper.properties       0.3s
 => [build 21/24] RUN ./mvnw -P with-c,with-dotnet,with-go,with-sandbo  3033.2s
 => ERROR [build 22/24] RUN ./mvnw -P with-c,with-dotnet,with-go,with-san  6.6s
------
 > [build 22/24] RUN ./mvnw -P with-c,with-dotnet,with-go,with-sandbox install:
#0 1.366 [INFO] Scanning for projects...
#0 2.941 [INFO] ------------------------------------------------------------------------
#0 2.943 [INFO] Reactor Build Order:
#0 2.944 [INFO] 
#0 2.946 [INFO] PLC4X                                                              [pom]
#0 2.949 [INFO] Code-Generation                                                    [pom]
#0 2.953 [INFO] Code-Generation: Protocol Base: MSpec                              [jar]
#0 2.956 [INFO] Code-Generation: Language Base: Freemarker                         [jar]
#0 2.959 [INFO] PLC4J                                                              [pom]
#0 2.961 [INFO] PLC4J: API                                                         [jar]
#0 2.963 [INFO] PLC4J: SPI                                                         [jar]
#0 2.965 [INFO] PLC4J: Transports                                                  [pom]
#0 2.968 [INFO] PLC4J: Transports: TCP                                             [jar]
#0 2.970 [INFO] PLC4J: Transports: Test                                            [jar]
#0 2.972 [INFO] PLC4J: Utils                                                       [pom]
#0 2.974 [INFO] PLC4J: Utils: Test Utils                                           [jar]
#0 2.975 [INFO] Code-Generation: Protocol Test: Test Mspec                         [jar]
#0 2.976 [INFO] Code-Generation: Language: Java                                    [jar]
#0 2.977 [INFO] Code-Generation: Language: C                                       [jar]
#0 2.978 [INFO] Code-Generation: Language: C#                                      [jar]
#0 2.979 [INFO] Code-Generation: Language: Go                                      [jar]
#0 2.980 [INFO] Protocols                                                          [pom]
#0 2.981 [INFO] Protocols: AB-ETH                                                  [jar]
#0 2.982 [INFO] Protocols: ADS                                                     [jar]
#0 2.983 [INFO] Protocols: C-Bus                                                   [jar]
#0 2.984 [INFO] Protocols: BACNet/IP                                               [jar]
#0 2.985 [INFO] Protocols: CANopen                                                 [jar]
#0 2.986 [INFO] Protocols: Df1                                                     [jar]
#0 2.987 [INFO] Protocols: EtherNet/IP                                             [jar]
#0 2.987 [INFO] Protocols: Firmata                                                 [jar]
#0 2.988 [INFO] Protocols: Generic CAN                                             [jar]
#0 2.989 [INFO] Protocols: KNXNet/IP                                               [jar]
#0 2.990 [INFO] Protocols: Modbus                                                  [jar]
#0 2.991 [INFO] Protocols: MQTT                                                    [jar]
#0 2.992 [INFO] Protocols: OPC UA                                                  [jar]
#0 2.993 [INFO] Protocols: Open-Protocol                                           [jar]
#0 2.994 [INFO] Protocols: PLC4X (Proxy)                                           [jar]
#0 2.996 [INFO] Protocols: PLC4X (API)                                             [jar]
#0 2.997 [INFO] Protocols: Profinet                                                [jar]
#0 2.998 [INFO] Protocols: S7                                                      [jar]
#0 2.999 [INFO] Protocols: Simulated                                               [jar]
#0 2.999 [INFO] Protocols: SocketCAN                                               [jar]
#0 3.000 [INFO] PLC4J: Drivers                                                     [pom]
#0 3.000 [INFO] PLC4J: Driver: AB-ETH                                              [jar]
#0 3.001 [INFO] PLC4J: Transports: Serial                                          [jar]
#0 3.001 [INFO] PLC4J: Driver: Beckhoff TwinCat ADS Driver                         [jar]
#0 3.002 [INFO] PLC4J: Transports: UDP                                             [jar]
#0 3.002 [INFO] PLC4J: Utils: Pcap (Shared)                                        [jar]
#0 3.002 [INFO] PLC4J: Transports: PCAP (shared)                                   [jar]
#0 3.003 [INFO] PLC4J: Utils: Raw-Sockets                                          [jar]
#0 3.003 [INFO] PLC4J: Transports: Raw Socket                                      [jar]
#0 3.003 [INFO] PLC4J: Utils: Pcap-Replay                                          [jar]
#0 3.004 [INFO] PLC4J: Transports: PCAP Replay                                     [jar]
#0 3.004 [INFO] PLC4J: Driver: S7 (Step7)                                          [jar]
#0 3.005 [INFO] PLC4J: Utils: Test-Generator                                       [jar]
#0 3.005 [INFO] PLC4J: Driver: BACNet/IP Driver                                    [jar]
#0 3.005 [INFO] PLC4J: Driver: C-Bus                                               [jar]
#0 3.006 [INFO] PLC4J: Transports: CAN                                             [jar]
#0 3.006 [INFO] PLC4J: Transports: SocketCAN                                       [jar]
#0 3.006 [INFO] PLC4J: Transports: VirtualCAN                                      [jar]
#0 3.007 [INFO] PLC4J: Driver: CAN                                              [bundle]
#0 3.007 [INFO] PLC4J: Driver: CANopen                                          [bundle]
#0 3.008 [INFO] PLC4J: Driver: Ethernet IP                                         [jar]
#0 3.008 [INFO] PLC4J: Driver: Firmata                                             [jar]
#0 3.008 [INFO] PLC4J: Driver: KNXNet/IP                                           [jar]
#0 3.008 [INFO] PLC4J: Driver: Mock                                                [jar]
#0 3.009 [INFO] PLC4J: Driver: Open-Protocol                                       [jar]
#0 3.009 [INFO] PLC4J: Driver: Modbus                                              [jar]
#0 3.009 [INFO] PLC4J: Driver: OPC UA                                              [jar]
#0 3.010 [INFO] PLC4J: Driver: PLC4X (Proxy-Protocol)                              [jar]
#0 3.010 [INFO] PLC4J: Driver: Profinet                                            [jar]
#0 3.010 [INFO] PLC4J: Driver: Simulated                                           [jar]
#0 3.010 [INFO] PLC4J: Examples                                                    [pom]
#0 3.011 [INFO] PLC4J: Examples: Hello-ADS telemetry                               [jar]
#0 3.011 [INFO] PLC4J: Examples: Cloud: Azure IoT Hub                              [jar]
#0 3.011 [INFO] PLC4J: Examples: Cloud: Google Cloud IoT Core                      [jar]
#0 3.011 [INFO] PLC4J: Examples: Hello Discovery                                   [jar]
#0 3.012 [INFO] PLC4J: Examples: Connectivity: MQTT                                [jar]
#0 3.012 [INFO] PLC4J: Examples: Hello InfluxDB Data Collection                    [jar]
#0 3.012 [INFO] PLC4J: Tools                                                       [pom]
#0 3.012 [INFO] PLC4J: Tools: Object PLC Mapping                                   [jar]
#0 3.012 [INFO] PLC4J: Tools: Connection Cache                                     [jar]
#0 3.013 [INFO] PLC4J: Examples: Hello OPM                                         [jar]
#0 3.013 [INFO] PLC4J: Examples: Hello-Webservice                                  [jar]
#0 3.013 [INFO] PLC4J: Examples: Hello-World: Kotlin                               [jar]
#0 3.014 [INFO] PLC4J: Examples: Hello-World PLC4X (Discover And Browse)           [jar]
#0 3.014 [INFO] PLC4J: Examples: Hello-World PLC4X (Read)                          [jar]
#0 3.014 [INFO] PLC4J: Examples: Hello-World PLC4X (Subscribe)                     [jar]
#0 3.014 [INFO] PLC4J: Examples: Hello-World PLC4X (Write)                         [jar]
#0 3.016 [INFO] PLC4J: Examples: Poll Loop Example                                 [jar]
#0 3.016 [INFO] PLC4J: Examples: S7Event example                                   [jar]
#0 3.016 [INFO] PLC4J: Tools: Scraper                                              [jar]
#0 3.016 [INFO] PLC4J: Integrations                                                [pom]
#0 3.016 [INFO] PLC4J: Integrations: Apache Calcite                                [jar]
#0 3.016 [INFO] PLC4J: Integrations: Apache Kafka                                  [jar]
#0 3.016 [INFO] PLC4J: Integrations: Apache Nifi                                   [pom]
#0 3.016 [INFO] PLC4J: Integrations: Apache Nifi: Processors                       [jar]
#0 3.017 [INFO] PLC4J: Integrations: Apache Nifi: NAR                              [nar]
#0 3.017 [INFO] PLC4J: Integrations: Eclipse Milo OPC UA Server                    [jar]
#0 3.017 [INFO] PLC4J: Tools: Capture Replay                                       [jar]
#0 3.017 [INFO] PLC4J: Tools: Plc4x Server                                         [jar]
#0 3.018 [INFO] PLC4J: Tools: Scraper (NG)                                         [jar]
#0 3.019 [INFO] PLC4J: Tools: UI                                                   [jar]
#0 3.019 [INFO] PLC4J: Utils: PLC-Simulator                                        [jar]
#0 3.019 [INFO] PLC4J: OSGi                                                        [jar]
#0 3.019 [INFO] PLC4C                                                              [pom]
#0 3.019 [INFO] PLC4Go                                                      [mvn-golang]
#0 3.019 [INFO] PLC4Net                                                            [pom]
#0 3.019 [INFO] Sandbox                                                            [pom]
#0 3.019 [INFO] Sandbox: PLC4J: Driver: Discovery                                  [jar]
#0 3.020 [INFO] Sandbox: Test Df1 Driver                                           [jar]
#0 3.035 [INFO] 
#0 3.035 [INFO] -------------------< org.apache.plc4x:plc4x-parent >--------------------
#0 3.035 [INFO] Building PLC4X 0.11.0-SNAPSHOT                                   [1/107]
#0 3.035 [INFO] --------------------------------[ pom ]---------------------------------
#0 3.100 [INFO] 
#0 3.100 [INFO] --- groovy-maven-plugin:2.1.1:execute (prerequisite-check) @ plc4x-parent ---
#0 3.302 Downloading from apache-releases: https://repository.apache.org/content/repositories/releases/net/java/dev/jna/jna/5.3.1/jna-5.3.1.pom
#0 4.028 Downloading from central: https://repo.maven.apache.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.pom (1.6 kB at 14 kB/s)
#0 4.180 Downloading from apache-releases: https://repository.apache.org/content/repositories/releases/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar
#0 4.180 Downloading from apache-releases: https://repository.apache.org/content/repositories/releases/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
#0 4.797 Downloading from central: https://repo.maven.apache.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar
#0 4.797 Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar (169 kB at 1.7 MB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar (1.5 MB at 8.5 MB/s)
#0 6.377 Os name:    Linux
#0 6.379 Os arch:    amd64
#0 6.381 Os version: 5.10.104-linuxkit
#0 6.409 Detected OS:   linux
#0 6.409 Detected Arch: x86_64
#0 6.420 
#0 6.423 Detecting Java version:    11.0.19        OK
#0 6.465 Detecting Dotnet version:  missing
#0 6.481 Detecting Git version:     2.34.1         OK
#0 6.490 Detecting Gcc version:     11.3.0         OK
#0 6.510 Detecting Maven version:   3.6.3          OK
#0 6.525 [INFO] ------------------------------------------------------------------------
#0 6.525 [INFO] Reactor Summary for PLC4X 0.11.0-SNAPSHOT:
#0 6.525 [INFO] 
#0 6.525 [INFO] PLC4X .............................................. FAILURE [  3.491 s]
#0 6.525 [INFO] Code-Generation .................................... SKIPPED
#0 6.526 [INFO] Code-Generation: Protocol Base: MSpec .............. SKIPPED
#0 6.526 [INFO] Code-Generation: Language Base: Freemarker ......... SKIPPED
#0 6.526 [INFO] PLC4J .............................................. SKIPPED
#0 6.526 [INFO] PLC4J: API ......................................... SKIPPED
#0 6.527 [INFO] PLC4J: SPI ......................................... SKIPPED
#0 6.527 [INFO] PLC4J: Transports .................................. SKIPPED
#0 6.527 [INFO] PLC4J: Transports: TCP ............................. SKIPPED
#0 6.527 [INFO] PLC4J: Transports: Test ............................ SKIPPED
#0 6.527 [INFO] PLC4J: Utils ....................................... SKIPPED
#0 6.528 [INFO] PLC4J: Utils: Test Utils ........................... SKIPPED
#0 6.528 [INFO] Code-Generation: Protocol Test: Test Mspec ......... SKIPPED
#0 6.528 [INFO] Code-Generation: Language: Java .................... SKIPPED
#0 6.528 [INFO] Code-Generation: Language: C ....................... SKIPPED
#0 6.529 [INFO] Code-Generation: Language: C# ...................... SKIPPED
#0 6.529 [INFO] Code-Generation: Language: Go ...................... SKIPPED
#0 6.529 [INFO] Protocols .......................................... SKIPPED
#0 6.530 [INFO] Protocols: AB-ETH .................................. SKIPPED
#0 6.530 [INFO] Protocols: ADS ..................................... SKIPPED
#0 6.530 [INFO] Protocols: C-Bus ................................... SKIPPED
#0 6.530 [INFO] Protocols: BACNet/IP ............................... SKIPPED
#0 6.530 [INFO] Protocols: CANopen ................................. SKIPPED
#0 6.531 [INFO] Protocols: Df1 ..................................... SKIPPED
#0 6.531 [INFO] Protocols: EtherNet/IP ............................. SKIPPED
#0 6.531 [INFO] Protocols: Firmata ................................. SKIPPED
#0 6.531 [INFO] Protocols: Generic CAN ............................. SKIPPED
#0 6.531 [INFO] Protocols: KNXNet/IP ............................... SKIPPED
#0 6.532 [INFO] Protocols: Modbus .................................. SKIPPED
#0 6.532 [INFO] Protocols: MQTT .................................... SKIPPED
#0 6.532 [INFO] Protocols: OPC UA .................................. SKIPPED
#0 6.532 [INFO] Protocols: Open-Protocol ........................... SKIPPED
#0 6.533 [INFO] Protocols: PLC4X (Proxy) ........................... SKIPPED
#0 6.533 [INFO] Protocols: PLC4X (API) ............................. SKIPPED
#0 6.533 [INFO] Protocols: Profinet ................................ SKIPPED
#0 6.533 [INFO] Protocols: S7 ...................................... SKIPPED
#0 6.533 [INFO] Protocols: Simulated ............................... SKIPPED
#0 6.534 [INFO] Protocols: SocketCAN ............................... SKIPPED
#0 6.534 [INFO] PLC4J: Drivers ..................................... SKIPPED
#0 6.534 [INFO] PLC4J: Driver: AB-ETH .............................. SKIPPED
#0 6.534 [INFO] PLC4J: Transports: Serial .......................... SKIPPED
#0 6.535 [INFO] PLC4J: Driver: Beckhoff TwinCat ADS Driver ......... SKIPPED
#0 6.535 [INFO] PLC4J: Transports: UDP ............................. SKIPPED
#0 6.535 [INFO] PLC4J: Utils: Pcap (Shared) ........................ SKIPPED
#0 6.535 [INFO] PLC4J: Transports: PCAP (shared) ................... SKIPPED
#0 6.535 [INFO] PLC4J: Utils: Raw-Sockets .......................... SKIPPED
#0 6.535 [INFO] PLC4J: Transports: Raw Socket ...................... SKIPPED
#0 6.535 [INFO] PLC4J: Utils: Pcap-Replay .......................... SKIPPED
#0 6.536 [INFO] PLC4J: Transports: PCAP Replay ..................... SKIPPED
#0 6.536 [INFO] PLC4J: Driver: S7 (Step7) .......................... SKIPPED
#0 6.536 [INFO] PLC4J: Utils: Test-Generator ....................... SKIPPED
#0 6.536 [INFO] PLC4J: Driver: BACNet/IP Driver .................... SKIPPED
#0 6.536 [INFO] PLC4J: Driver: C-Bus ............................... SKIPPED
#0 6.537 [INFO] PLC4J: Transports: CAN ............................. SKIPPED
#0 6.537 [INFO] PLC4J: Transports: SocketCAN ....................... SKIPPED
#0 6.537 [INFO] PLC4J: Transports: VirtualCAN ...................... SKIPPED
#0 6.537 [INFO] PLC4J: Driver: CAN ................................. SKIPPED
#0 6.537 [INFO] PLC4J: Driver: CANopen ............................. SKIPPED
#0 6.537 [INFO] PLC4J: Driver: Ethernet IP ......................... SKIPPED
#0 6.538 [INFO] PLC4J: Driver: Firmata ............................. SKIPPED
#0 6.538 [INFO] PLC4J: Driver: KNXNet/IP ........................... SKIPPED
#0 6.538 [INFO] PLC4J: Driver: Mock ................................ SKIPPED
#0 6.538 [INFO] PLC4J: Driver: Open-Protocol ....................... SKIPPED
#0 6.538 [INFO] PLC4J: Driver: Modbus .............................. SKIPPED
#0 6.538 [INFO] PLC4J: Driver: OPC UA .............................. SKIPPED
#0 6.538 [INFO] PLC4J: Driver: PLC4X (Proxy-Protocol) .............. SKIPPED
#0 6.538 [INFO] PLC4J: Driver: Profinet ............................ SKIPPED
#0 6.539 [INFO] PLC4J: Driver: Simulated ........................... SKIPPED
#0 6.539 [INFO] PLC4J: Examples .................................... SKIPPED
#0 6.539 [INFO] PLC4J: Examples: Hello-ADS telemetry ............... SKIPPED
#0 6.539 [INFO] PLC4J: Examples: Cloud: Azure IoT Hub .............. SKIPPED
#0 6.539 [INFO] PLC4J: Examples: Cloud: Google Cloud IoT Core ...... SKIPPED
#0 6.540 [INFO] PLC4J: Examples: Hello Discovery ................... SKIPPED
#0 6.540 [INFO] PLC4J: Examples: Connectivity: MQTT ................ SKIPPED
#0 6.540 [INFO] PLC4J: Examples: Hello InfluxDB Data Collection .... SKIPPED
#0 6.540 [INFO] PLC4J: Tools ....................................... SKIPPED
#0 6.540 [INFO] PLC4J: Tools: Object PLC Mapping ................... SKIPPED
#0 6.540 [INFO] PLC4J: Tools: Connection Cache ..................... SKIPPED
#0 6.540 [INFO] PLC4J: Examples: Hello OPM ......................... SKIPPED
#0 6.541 [INFO] PLC4J: Examples: Hello-Webservice .................. SKIPPED
#0 6.541 [INFO] PLC4J: Examples: Hello-World: Kotlin ............... SKIPPED
#0 6.541 [INFO] PLC4J: Examples: Hello-World PLC4X (Discover And Browse) SKIPPED
#0 6.541 [INFO] PLC4J: Examples: Hello-World PLC4X (Read) .......... SKIPPED
#0 6.541 [INFO] PLC4J: Examples: Hello-World PLC4X (Subscribe) ..... SKIPPED
#0 6.541 [INFO] PLC4J: Examples: Hello-World PLC4X (Write) ......... SKIPPED
#0 6.541 [INFO] PLC4J: Examples: Poll Loop Example ................. SKIPPED
#0 6.541 [INFO] PLC4J: Examples: S7Event example ................... SKIPPED
#0 6.542 [INFO] PLC4J: Tools: Scraper .............................. SKIPPED
#0 6.542 [INFO] PLC4J: Integrations ................................ SKIPPED
#0 6.542 [INFO] PLC4J: Integrations: Apache Calcite ................ SKIPPED
#0 6.542 [INFO] PLC4J: Integrations: Apache Kafka .................. SKIPPED
#0 6.542 [INFO] PLC4J: Integrations: Apache Nifi ................... SKIPPED
#0 6.542 [INFO] PLC4J: Integrations: Apache Nifi: Processors ....... SKIPPED
#0 6.542 [INFO] PLC4J: Integrations: Apache Nifi: NAR .............. SKIPPED
#0 6.542 [INFO] PLC4J: Integrations: Eclipse Milo OPC UA Server .... SKIPPED
#0 6.543 [INFO] PLC4J: Tools: Capture Replay ....................... SKIPPED
#0 6.543 [INFO] PLC4J: Tools: Plc4x Server ......................... SKIPPED
#0 6.543 [INFO] PLC4J: Tools: Scraper (NG) ......................... SKIPPED
#0 6.543 [INFO] PLC4J: Tools: UI ................................... SKIPPED
#0 6.543 [INFO] PLC4J: Utils: PLC-Simulator ........................ SKIPPED
#0 6.543 [INFO] PLC4J: OSGi ........................................ SKIPPED
#0 6.543 [INFO] PLC4C .............................................. SKIPPED
#0 6.543 [INFO] PLC4Go ............................................. SKIPPED
#0 6.544 [INFO] PLC4Net ............................................ SKIPPED
#0 6.544 [INFO] Sandbox ............................................ SKIPPED
#0 6.544 [INFO] Sandbox: PLC4J: Driver: Discovery .................. SKIPPED
#0 6.544 [INFO] Sandbox: Test Df1 Driver ........................... SKIPPED
#0 6.544 [INFO] ------------------------------------------------------------------------
#0 6.545 [INFO] BUILD FAILURE
#0 6.545 [INFO] ------------------------------------------------------------------------
#0 6.545 [INFO] Total time:  5.198 s
#0 6.545 [INFO] Finished at: 2023-05-14T10:38:28Z
#0 6.545 [INFO] ------------------------------------------------------------------------
#0 6.547 [ERROR] Failed to execute goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute (prerequisite-check) on project plc4x-parent: Execution prerequisite-check of goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute failed: Not all conditions met, see log for details. -> [Help 1]
#0 6.547 [ERROR] 
#0 6.547 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#0 6.547 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#0 6.548 [ERROR] 
#0 6.548 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#0 6.548 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
------
error: failed to solve: executor failed running [/bin/sh -c ./mvnw -P with-c,with-dotnet,with-go,with-sandbox install]: exit code: 1
[3053500 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/8c/p7071m455b50dlw2ysfy09wh0000gn/T/devcontainercli/container-features/0.25.2-1684057660828/Dockerfile-with-features -t vsc-plc4x-6c96a59745bbe99b04bc3352976595f7 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/maneet/Documents/plc4x
[3053500 ms]     at Doe (/Users/maneet/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1894:1669)
[3053500 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[3053500 ms]     at async EF (/Users/maneet/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1978)
[3053500 ms]     at async uT (/Users/maneet/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:901)
[3053500 ms]     at async Poe (/Users/maneet/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:2128)
[3053500 ms]     at async Zf (/Users/maneet/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:3278)
[3053501 ms]     at async aue (/Users/maneet/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15276)
[3053501 ms]     at async oue (/Users/maneet/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15030)
[3053511 ms] Exit code 1
[3053517 ms] Command failed: /private/var/folders/8c/p7071m455b50dlw2ysfy09wh0000gn/T/AppTranslocation/A1FB6412-9C8E-44B8-B1FF-BECAD0950EF1/d/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/maneet/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/maneet/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/maneet/Documents/plc4x --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/maneet/Documents/plc4x --log-level debug --log-format json --config /Users/maneet/Documents/plc4x/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[3053517 ms] Exit code 1
```

Getting the above error when I try to create a Docker dev environment using the Dockerfile in the root directory.

**Comment by maneetgoyal** [comment]
@sruehl @chrisdutz Any suggestions please? Hard to get the build going via Docker. I can share more details if needed.

**Comment by sruehl** [comment]
Seems that the build doesn't detect dotnet anymore. @chrisdutz any idea?

**Comment by sruehl** [comment]
I'll add a ouput in case that happens so It is easier to debug the problem...

**Comment by sruehl** [comment]
@maneetgoyal can you retry with the latest develop revision? 62478b88010805d8d718f4f7c151207e20f7cb2e

**Comment by maneetgoyal** [comment]
> @maneetgoyal can you retry with the latest develop revision? [62478b8](https://github.com/apache/plc4x/commit/62478b88010805d8d718f4f7c151207e20f7cb2e)

Sure, will try in a bit

**Comment by sruehl** [comment]
Also the issue you are having is unrelated to this one. @maneetgoyal Can you please open a new issue and append the output there?

With the output is verified that `mvnw` works

**Comment by maneetgoyal** [comment]
> Also the issue you are having is unrelated to this one. @maneetgoyal Can you please open a new issue and append the output there?
> 
> With the output is verified that `mvnw` works

Sounds good.

The command is taking long to complete, will post once done. Current at:

```
 => [build 21/24] RUN ./mvnw -P with-c,with-dotnet,with-go,with-sandbox  1279.0s
 => => # en-aether-provider-3.2.5.jar                                           / => => # Downloaded from apache-releases: https://repository.apache.org/content/
 => => # repositories/releases/org/apache/maven/reporting/maven-reporting-exec/19 => => # .6.0/maven-reporting-exec-1.6.0.jar (31 kB at 22 kB/s)                 
 => => # Downloading from apache-re                                             9 => => # [output clipped, log limit 1MiB reached]
```
